services:

  db:
    container_name: db_postgres
    image: postgres
    volumes:
      - /volumes/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env
    restart: unless-stopped

  nginx:
    container_name: nginx_proxy
    image: nginx
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a.seleznev@avgr.su
      PGADMIN_DEFAULT_PASSWORD: 23As9080
      # PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  web:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    volumes:
      - .:/app
    # ports:
    #   - "8080:8080"
    network_mode: host
    env_file:
      - ./.env
    depends_on:
      - db
    restart: unless-stopped
  
volumes:
  db:
  pgadmin-data:
  nginx:
  web:

