"""empty message

Revision ID: 6f5d4779546b
Revises: 7a10f2a2ad73
Create Date: 2024-07-15 17:11:05.381801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f5d4779546b"
down_revision: Union[str, None] = "7a10f2a2ad73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_username", table_name="api_users")
    op.create_index(
        op.f("ix_api_users_username"), "api_users", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_users_username"), table_name="api_users")
    op.create_index("ix_users_username", "api_users", ["username"], unique=True)
    # ### end Alembic commands ###
